apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
    tier: postgresql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgresql:5.6
          name: postgresql
          env:
            - name: postgresql_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config-map
                  key: postgresql-database-name
            - name: postgresql_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-pass
                  key: postgresql-root-password
            - name: postgresql_USER
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config-map
                  key: postgresql-user-username
            - name: postgresql_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-pass
                  key: postgresql-user-password
          livenessProbe:
            tcpSocket:
              port: 5432
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql-persistent-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: postgresql-pvc